In [3]:
from numpy.random import seed 
seed(1) 
from tensorflow import set_random_seed 
set_random_seed(2)
import keras

from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
#from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.svm import SVC
svm_model= SVC()
from sklearn.preprocessing import StandardScaler
#from numpy.random import seed
#seed(1)

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
x_train = np.genfromtxt('/Users/ombahiwal/PycharmProjects/test_kvb/omkar/CNN/train2/x_train.csv',delimiter=",")
y_train = np.genfromtxt('/Users/ombahiwal/PycharmProjects/test_kvb/omkar/CNN/train2/y_train.csv',delimiter=",")

x_test = np.genfromtxt('/Users/ombahiwal/PycharmProjects/test_kvb/omkar/CNN/train2/x_test.csv',delimiter=",")
y_test = np.genfromtxt('/Users/ombahiwal/PycharmProjects/test_kvb/omkar/CNN/train2/y_test.csv',delimiter=",")

In [4]:
#Support Vector Machine without polynomial kernel
tuned_parameters = {
 'C': [1, 10, 100,500, 1000], 'kernel': ['linear','rbf'],
 'C': [1, 10, 100,500, 1000], 'gamma': [1,0.1,0.01,0.001, 0.0001], 'kernel': ['rbf'],
 #'degree': [2,3,4,5,6] , 'C':[1,10,100,500,1000] , 'kernel':['poly']
    }

In [5]:
from sklearn.model_selection import RandomizedSearchCV
model_svm = RandomizedSearchCV(svm_model, tuned_parameters,cv=10,scoring='accuracy',n_iter=20)
print(x_train)

[[ 9.37815253 -0.24943754 -7.3383299  ... -0.11936099 -0.4741766
   0.03899424]
 [ 1.12205785 -0.77647955 -3.39432006 ... -0.12118604  0.41831302
  -0.39720682]
 [-4.10980835  7.1403527  -2.4022703  ... -0.0699018  -0.16162688
  -0.02932583]
 ...
 [ 9.95619185 12.9309428  11.19465961 ...  0.53512483 -0.35088907
  -0.26305556]
 [ 8.26711508  6.66716042  9.44290216 ...  0.28525675  0.02208326
   0.28181373]
 [ 5.87644443  2.25542821  9.15078605 ...  0.85203793 -0.21414645
   0.1388367 ]]


In [6]:
model_svm.fit(x_train, y_train)
print(model_svm.best_score_)

0.9866666666666667


/Library/Python/2.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [7]:
# grid_scores_ to cv_results
print(model_svm.cv_results_)

{'std_train_score': array([0.0167665 , 0.00674487, 0.00182623, 0.00964601, 0.00182623,
       0.00182623, 0.00182623, 0.00668248, 0.02556407, 0.0149674 ,
       0.00182623, 0.00182623, 0.00182623, 0.00182623, 0.00182623,
       0.00182623, 0.00182623, 0.00182623, 0.00671104, 0.00182623]), 'split4_test_score': array([0.73333333, 0.9       , 0.96666667, 0.73333333, 0.96666667,
       0.96666667, 0.96666667, 0.76666667, 0.53333333, 0.7       ,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.96666667, 0.73333333, 0.96666667]), 'mean_train_score': array([0.85406219, 0.98110126, 0.99406988, 0.72146873, 0.99406988,
       0.99406988, 0.99406988, 0.92147204, 0.54818988, 0.87774435,
       0.99406988, 0.99406988, 0.99406988, 0.99406988, 0.99406988,
       0.99406988, 0.99406988, 0.99406988, 0.95592795, 0.99406988]), 'split0_train_score': array([0.88104089, 0.97026022, 0.99256506, 0.72118959, 0.99256506,
       0.99256506, 0.99256506, 0.9219330

In [8]:
print(model_svm.best_params_)

{'kernel': 'rbf', 'C': 500, 'gamma': 0.01}


In [9]:
y_pred= model_svm.predict(x_test)
print(metrics.accuracy_score(y_pred,y_test))
print(y_pred)
print(y_test)

0.64
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 2. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 2. 0. 2. 0. 0. 2. 2. 2. 1. 0. 1. 1. 1. 0. 1. 2. 2. 2. 1. 2. 2. 2. 2.
 2. 2. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 1. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 1. 0. 2. 0. 2. 0. 0. 2. 2. 2. 1. 0. 1. 1. 1. 0. 1. 2. 2. 2. 1.
 2. 2. 2. 2. 2. 2. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0

In [10]:
confusion_matrix=metrics.confusion_matrix(y_test,y_pred)
confusion_matrix

array([[88,  8,  8],
       [28, 12,  0],
       [16, 12, 28]])

In [11]:
auc_roc=metrics.classification_report(y_test,y_pred)
auc_roc

u'              precision    recall  f1-score   support\n\n         0.0       0.67      0.85      0.75       104\n         1.0       0.38      0.30      0.33        40\n         2.0       0.78      0.50      0.61        56\n\n   micro avg       0.64      0.64      0.64       200\n   macro avg       0.61      0.55      0.56       200\nweighted avg       0.64      0.64      0.62       200\n'

# Support Vector machine with polynomial Kernel

In [12]:
from sklearn.model_selection import RandomizedSearchCV

model_svm = RandomizedSearchCV(svm_model, tuned_parameters,cv=10,scoring='accuracy',n_iter=20)

In [13]:
model_svm.fit(x_train, y_train)
print(model_svm.best_score_)

0.9866666666666667


/Library/Python/2.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [14]:
print(model_svm.cv_results_)

{'std_train_score': array([0.00182623, 0.00964601, 0.00182623, 0.00668248, 0.00182623,
       0.00182623, 0.00182623, 0.00182623, 0.00182623, 0.00182623,
       0.00182623, 0.00671104, 0.0167665 , 0.00182623, 0.01441295,
       0.00182623, 0.02556407, 0.00182623, 0.00182623, 0.0149674 ]), 'split4_test_score': array([0.96666667, 0.73333333, 0.96666667, 0.76666667, 0.96666667,
       0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
       0.96666667, 0.73333333, 0.73333333, 0.96666667, 0.76666667,
       0.96666667, 0.53333333, 0.96666667, 0.96666667, 0.7       ]), 'mean_train_score': array([0.99406988, 0.72146873, 0.99406988, 0.92147204, 0.99406988,
       0.99406988, 0.99406988, 0.99406988, 0.99406988, 0.99406988,
       0.99406988, 0.95592795, 0.85406219, 0.99406988, 0.87554939,
       0.99406988, 0.54818988, 0.99406988, 0.99406988, 0.87774435]), 'split0_train_score': array([0.99256506, 0.72118959, 0.99256506, 0.92193309, 0.99256506,
       0.99256506, 0.99256506, 0.9925650

In [15]:
# print(model_svm.grid_scores_)

In [16]:
print(model_svm.best_params_)

{'kernel': 'rbf', 'C': 500, 'gamma': 0.001}


In [17]:
y_pred= model_svm.predict(x_test)
print(metrics.accuracy_score(y_pred,y_test))

0.61


In [18]:
confusion_matrix=metrics.confusion_matrix(y_test,y_pred)
confusion_matrix


array([[80, 14, 10],
       [28, 12,  0],
       [12, 14, 30]])

In [19]:
auc_roc=metrics.classification_report(y_test,y_pred)
auc_roc

u'              precision    recall  f1-score   support\n\n         0.0       0.67      0.77      0.71       104\n         1.0       0.30      0.30      0.30        40\n         2.0       0.75      0.54      0.63        56\n\n   micro avg       0.61      0.61      0.61       200\n   macro avg       0.57      0.53      0.55       200\nweighted avg       0.62      0.61      0.61       200\n'

# Support Vector Machine without polynomial kernel

In [20]:
tuned_parameters = {
 'C': [1, 10, 100,500, 1000], 'kernel': ['linear','rbf'],
 'C': [1, 10, 100,500, 1000], 'gamma': [1,0.1,0.01,0.001, 0.0001], 'kernel': ['rbf'],
 #'degree': [2,3,4,5,6] , 'C':[1,10,100,500,1000] , 'kernel':['poly']
    }
from sklearn.model_selection import RandomizedSearchCV

model_svm = RandomizedSearchCV(svm_model, tuned_parameters,cv=10,scoring='accuracy',n_iter=20)

In [22]:
model_svm.fit(x_train, y_train)
print(model_svm.best_score_)

0.9866666666666667


/Library/Python/2.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [23]:
# grid_scores to cv_results_
print(model_svm.cv_results_)

{'std_train_score': array([0.0149674 , 0.00182623, 0.02556407, 0.00182623, 0.00182623,
       0.00182623, 0.00182623, 0.00668248, 0.00182623, 0.00674487,
       0.00964601, 0.00182623, 0.00182623, 0.00766552, 0.00671104,
       0.0167665 , 0.00182623, 0.00182623, 0.00182623, 0.00182623]), 'split4_test_score': array([0.7       , 0.96666667, 0.53333333, 0.96666667, 0.96666667,
       0.96666667, 0.96666667, 0.76666667, 0.96666667, 0.9       ,
       0.73333333, 0.96666667, 0.96666667, 0.73333333, 0.73333333,
       0.73333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667]), 'mean_train_score': array([0.87774435, 0.99406988, 0.54818988, 0.99406988, 0.99406988,
       0.99406988, 0.99406988, 0.92147204, 0.99406988, 0.98110126,
       0.72146873, 0.99406988, 0.99406988, 0.69555464, 0.95592795,
       0.85406219, 0.99406988, 0.99406988, 0.99406988, 0.99406988]), 'split0_train_score': array([0.88104089, 0.99256506, 0.58736059, 0.99256506, 0.99256506,
       0.99256506, 0.99256506, 0.9219330

In [25]:
print(model_svm.best_params_)

{'kernel': 'rbf', 'C': 500, 'gamma': 1}


In [26]:
y_pred= model_svm.predict(x_test)
print(metrics.accuracy_score(y_pred,y_test))

0.52


In [27]:
confusion_matrix=metrics.confusion_matrix(y_test,y_pred)
confusion_matrix

array([[104,   0,   0],
       [ 40,   0,   0],
       [ 56,   0,   0]])

In [28]:
auc_roc=metrics.classification_report(y_test,y_pred)
auc_roc

/Library/Python/2.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


u'              precision    recall  f1-score   support\n\n         0.0       0.52      1.00      0.68       104\n         1.0       0.00      0.00      0.00        40\n         2.0       0.00      0.00      0.00        56\n\n   micro avg       0.52      0.52      0.52       200\n   macro avg       0.17      0.33      0.23       200\nweighted avg       0.27      0.52      0.36       200\n'

# Random Forest Classifier

In [29]:
from sklearn.ensemble import RandomForestClassifier

model_RR=RandomForestClassifier()

#tuned_parameters = {'min_samples_leaf': range(5,10,5), 'n_estimators' : range(50,200,50),
                    #'max_depth': range(5,15,5), 'max_features':range(5,20,5)
                    #}
               

In [31]:
model_RR.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [32]:
y_prob = model_RR.predict_proba(x_test)[:,1] # This will give you positive class prediction probabilities  
y_pred = np.where(y_prob > 0.5, 1, 0) # This will threshold the probabilities to give class predictions.
model_RR.score(x_test, y_pred)

0.73

In [33]:
confusion_matrix=metrics.confusion_matrix(y_test,y_pred)
confusion_matrix

array([[104,   0,   0],
       [ 40,   0,   0],
       [ 54,   2,   0]])

In [34]:
auc_roc = metrics.classification_report(y_test,y_pred)
auc_roc

u'              precision    recall  f1-score   support\n\n         0.0       0.53      1.00      0.69       104\n         1.0       0.00      0.00      0.00        40\n         2.0       0.00      0.00      0.00        56\n\n   micro avg       0.52      0.52      0.52       200\n   macro avg       0.18      0.33      0.23       200\nweighted avg       0.27      0.52      0.36       200\n'